### ISSUE TITLE
Availablity of machine-readable "Table of Action categories"

### ISSUE THREAD

**Issue by felixdivo** [abhinanda-punnakkal/BABEL#10]
Is the ["Table of Action categories"](https://babel.is.tue.mpg.de/actionsrawlabels.html) available in a simple machine-readable format (JSON, ...) too?

**Comment by carjun** [comment]
We do not have a ready-to-use JSON version of this data, but it should be quick for you to create. 

Basically, what you're looking for is a mapping between `raw_label` and `act_cat` in a BABEL annotation (e.g., below). You can loop over each annotation in the dataset, and create a dictionary of `{<act_cat>: [ <raw_label_1>, <raw_label_2>, ... ], ... }`

```
"raw_label": "walk back and forth",
"proc_label": "walk back and forth",
"seg_id": "3ca74412-f765-445b-b51b-6c2e72316010",
"act_cat": [
  "walk",
  "forward movement",
  "backwards movement"
]
```

Hope this answers your question!

**Comment by felixdivo** [comment]
Okay, thank you!

**Comment by felixdivo** [comment]
@carjun Would I be allowed to publish this extracted data (and nothing else of the data, of course)? E.g. in a MIT-licensed GitHub repo?
