### ISSUE TITLE
test.json

### ISSUE THREAD

**Issue by Jaceyxy** [abhinanda-punnakkal/BABEL#11]
thansks for your great job!
However,when I loaded the test.json file into my Python script, I noticed that all the activity labels were NaN, both for sequence and frame-level labels.Can you tell me the reason?

**Comment by carjun** [comment]
Thanks @Jaceyxy . We are using the test set (samples from test.json) for the BABEL Action Recognition Challenge: https://babel-evaluation.is.tuebingen.mpg.de/ . So the ground-truth labels are held-out, and not publicly available.

**Comment by Jaceyxy** [comment]
thanks！
