### ISSUE TITLE
how to generate joint_pose in create_dataset.py ？

### ISSUE THREAD

**Issue by MengHao666** [abhinanda-punnakkal/BABEL#12]
Could you provide the code of generte [it](https://github.com/abhinanda-punnakkal/BABEL/blob/38d8fa9dedfa4a614f2e03604fcb044621e14ee3/action_recognition/data_gen/create_dataset.py#L221) ? 
I am very confused about [it](https://github.com/abhinanda-punnakkal/BABEL/blob/main/action_recognition/data_gen/dutils.py#L92).
I could only get 52 joints of SMPLH model with [human-body-prior](https://github.com/nghorbani/human_body_prior). How could you do it?

**Comment by carjun** [comment]
Hi @MengHao666 ! 
(1) You might find code in the [SMPLX repo](https://github.com/vchoutas/smplx) useful if you'd like to generate joint positions from the AMASS npz file with joint rotations. Specifically, instantiate the SMPLH body model (class definition is [here](https://github.com/vchoutas/smplx/blob/c63c02b478c5c6f696491ed9167e3af6b08d89b1/smplx/body_models.py#L395)). Then, call the `forward` function [here](https://github.com/vchoutas/smplx/blob/c63c02b478c5c6f696491ed9167e3af6b08d89b1/smplx/body_models.py#L568) with the pose (rotations) as argument. This function should return the joint positions. 
(2) Yes, there is no 1-1 mapping between all the joints in SMPLH skeleton format and the NTU skeleton format. So to get the locations of certain joints of the NTU skeleton, we actually obtain the corresponding vertices from the full mesh. We obtain the locations in the mesh using the same forward function described in (1).
