### ISSUE TITLE
About test.json

### ISSUE THREAD

**Issue by eanson023** [abhinanda-punnakkal/BABEL#13]
Hi Author,

Thank you very much for bringing such a wonderful work. This dataset makes it possible to complete many new tasks, such as temporal sentence grounding in motions, but I did not find the frame-level label in the test.json file , only time starts/ends. I read the issue and found that the reason why the tags are not public is that the action recognition challenge is still in progress, so I would like to ask if you will consider releasing the tag data of test.json in the future. If so, is there a specific time. Thanks again!

Best,
eanson

**Comment by carjun** [comment]
Hi @eanson023 , thanks for your interest. As of now, we do not plan to publicly release the test set's ground-truth labels. We hope that the training and validation data will be sufficient for the purposes of your task. 

In case you are also planning to create a challenge task for the community with our held-out test set, we are open to discussing this further. Feel free to contact us via email. Thanks!

**Comment by eanson023** [comment]
ok， i see， thank you！
