### ISSUE TITLE
Access to AMASS SMPL parameters

### ISSUE THREAD

**Issue by BrianG13** [abhinanda-punnakkal/BABEL#2]
Hi,
1st I want to thank you guys for releasing the code + data, this is not obvious at all and I appreciate the effort, I am sure it will be useful.
I am wondering as in the example notebooks uploaded there are some missing examples:
- How can I access to the SMPL parameters of the actions? (How the mapping to AMASS dataset work? What should I download from their site?)
- There are frames annotations for the actions? I see on the examples only: `start_t` & `end_t` . There is a `start_frame` anywhere?

Thanks for your help!

**Comment by h-bouzid** [comment]
Hi,

Have you found the solution to this issue please ? 

Thanks for responding.

**Comment by abhinanda-punnakkal** [comment]
Hi @BrianG13 , @BOUZID-Hamza , 

Thank you both for your questions. 

- Babel is built upon the AMASS dataset and you need to download it from [here](https://amass.is.tue.mpg.de/).  An example data entry from BABEL looks like: 
![image](https://github.com/abhinanda-punnakkal/BABEL/assets/38729187/b3a6de89-00a9-48e8-a113-bd884f227cb6)
Here, the field `"feat_p"` points to the rrelative path of SMPL pose parameters.
BABEL data format is explained in this [link ](https://babel.is.tue.mpg.de/data.html).


- BABEL was collected by showing videos of actions rendered at 30 FPS. Hence, the annotation consists of `start_t ` &  `start_t `. 

Hope this answered your questions.

**Comment by h-bouzid** [comment]
alright. I was confused where can I find all the "npz" files. But they are all in the AMASS archive. Thank you very much for you time and effort.
