### ISSUE TITLE
About 5-second motions with repeated sub-actions.

### ISSUE THREAD

**Issue by cotton-ahn** [abhinanda-punnakkal/BABEL#3]
I am one of the people who are interested in this dataset. To participate in the challenge of action recognition, I've tried to download the pre-processed pickle file and tried to plot it.

But when I plot one of the motions in the npz file, I've observed that several 5-second motions are just repeating the same sub-action segment. 

For example, when I tried to plot the npy1[17].transpose(1, 2, 0, 3)[:, :, :, 0], where npy1 = np.load('./train_ntu_sk_60.npy'),

The plotted result shows the human just keep moving own's hands for 5 seconds.

But in the paper, it says "If the Kth chunk XKs has duration< 5 sec., we repeat XKs, and truncate at 5 sec."

What I see is a big gap between the code and paper. Could you explain why this happens in the preprocessed dataset?

And also, could you explain what is "chunk_id"? I cannot find more information about this. It seems like the order of the chunk when dividing the whole sequence into 5 seconds of segments, but I am still not sure about this.

**Comment by carjun** [comment]
Hi @cotton-ahn, thanks for your interest in our work. 

The 2S-AGCN model only accepts a 5-second input. So, we chunk a longer motion sequence $X_s$ into a sequence of 5-second chunks $X_s = (X^1_s, X^2_s, …, X^K_s)$. Here, the superscript of each 5-second chunk denotes the chunk ID. So this particular sequence has a total of K chunks. 

It is often the case that the K-th chunk is less than 5 seconds long. So we repeat the chunk to form a longer motion, e.g., $\tilde{X}^K_s = [X^K_s, X^K_s, X^K_s, …. ]$ (concatenate along the time axis). Finally, we truncate the sequence $\tilde{X}^K_s$ at 5 seconds. This processing follows the 2S-AGCN paper’s handling of sequences (from NTU-RGBD). 

Given this processing, it is natural that there exist 5-second chunks where a small movement is repeated a few times.
