### ISSUE TITLE
Count of action segments doesn't match with the bar graph provided on the website

### ISSUE THREAD

**Issue by chinnusai25** [abhinanda-punnakkal/BABEL#5]
We used the babel json files and generated the count of action segments using all the json files (i.e train, val, test, extra_train, extra_val) but the distribution we got is not matching with that of website plot provided at https://babel.is.tue.mpg.de/media/upload/stats/h_action_category_counts.svg
NOTE : We used frame_ann act_cat to count the action segments and if it was None we used seq_ann act_cat
NOTE : As per the table in this link https://babel.is.tue.mpg.de/actionsrawlabels.html, there should be 271 action categories but we were getting only 251 unique action categories.
Count of action segments we got is as follows,
Total action segments : 251
Count of action segments : {'endure': 1, 'lead': 1, 'bartender behavior series': 1, 'admire': 1, 'slash gesture series': 1, 'plant feet': 1, 'try': 1, 'vomit': 1, 'dive': 1, 'cower': 1, 'read': 1, 'agressive actions series': 1, 'cradle': 1, 'blow': 1, 'puppeteer': 1, 'shout': 2, 'curtsy': 2, 'navigate': 2, 'glide': 2, 'reveal': 2, 'smell': 2, 'plead': 2, 'stick': 2, 'backwards': 2, 'count': 2, 'feet movements': 2, 'fly': 2, 'weave': 2, 'come': 2, 'follow': 2, 'fill': 2, 'charge': 3, 'pat': 3, 'moonwalk': 3, 'uncross': 3, 'fidget': 3, 'lick': 3, 'taunt': 3, 'hiccup': 3, 'leave': 3, 'sleep': 3, 'fire gun': 4, 'headstand': 4, 'cut': 4, 'excite': 4, 'disagree': 5, 'celebrate': 5, 'gain': 5, 'despair': 5, 'skate': 5, 'laugh': 5, 'sneeze': 5, 'tentative movements': 5, 'zip/unzip': 5, 'chop': 6, 'conduct': 6, 'shave': 7, 'steady': 7, 'operate interface': 7, 'ride': 7, 'rolls on ground': 7, 'remove': 8, 'cough': 8, 'hang': 8, 'juggle': 8, 'worry': 8, 'flail arms': 8, 'aim': 9, 'yawn': 9, 'chicken dance': 9, 'fish': 9, 'pose': 9, 'dip': 9, 'prepare': 9, 'rocking movement': 10, 'write': 11, 'release': 11, 'unknown': 11, 'inward motion': 11, 'listen': 11, 'drive': 11, 'close something': 11, 'hurry': 11, 'clasp hands': 12, 'think': 13, 'hug': 13, 'cry': 13, 'handstand': 13, 'wobble': 14, 'strafe': 14, 'shivering': 15, 'sign': 15, 'bump': 15, 'zombie': 16, 'drunken behavior': 16, 'interact with rope': 17, 'pray': 17, 'stroke': 17, 'tiptoe': 17, 'swipe': 18, 'fall': 18, 'tie': 18, 'stomp': 19, 'noisy labels': 19, 'waddle': 19, 'draw': 20, 'get injured': 20, 'eat': 21, 'fight': 21, 'wash': 21, 'wiggle': 23, 'style hair': 24, 'check': 24, 'search': 24, 'flip': 26, 'march': 26, 'list body parts': 26, 'mime': 29, 'leap': 29, 'duck': 29, 'move misc. body part': 32, 'relax': 32, 'misc. action': 32, 'shrug': 33, 'slide': 34, 'salute': 35, 'stagger': 38, 'play': 38, 'sudden movement': 39, 'to lower a body part': 40, 'wait': 40, 'open something': 41, 'flap': 41, 'dribble': 42, 'protect': 43, 'sway': 43, 'lunge': 44, 'limp': 45, 'give something': 45, 'cartwheel': 46, 'rub': 46, 'shuffle': 46, 'misc. abstract action': 46, 'golf': 47, 'sneak': 48, 'mix': 49, 'misc. activities': 52, 'side to side movement': 52, 'wrist movements': 53, 'trip': 54, 'stances': 55, 'skip': 56, 'press something': 57, 'jump rope': 60, 'communicate (vocalise)': 62, 'spread': 63, 'swim': 63, 'lie': 65, 'drink': 68, 'point': 72, 'tap': 73, 'yoga': 74, 'jumping jacks': 84, 'shoulder movements': 84, 'evade': 85, 'rolling movement': 86, 'play catch': 87, 'support': 93, 'touch ground': 94, 'telephone call': 96, 'grab person': 97, 'stop': 97, 'move back to original position': 104, 'twist': 107, 'adjust': 109, 'play instrument': 109, 'animal behavior': 112, 'bow': 113, 'upper body movements': 125, 'hit': 135, 'grab body part': 150, 'crawl': 150, 'knock': 151, 'crouch': 153, 'kneel': 162, 'martial art': 162, 'face direction': 165, 'spin': 165, 'balance': 187, 'crossing limbs': 192, 'shake': 192, 'clap': 196, 'punch': 226, 'hop': 228, 'clean something': 243, 'stumble': 245, 'squat': 248, 'scratch': 250, 'play sport': 261, 'touching face': 264, 'poses': 266, 'catch': 270, 'sports move': 287, 'lean': 297, 'swing body part': 312, 'perform': 321, 'knee movement': 324, 'waist movements': 326, 'lift something': 343, 'move something': 364, 'grasp object': 398, 'greet': 411, 'exercise/training': 418, 'wave': 468, 'head movements': 479, 'dance': 499, 'a pose': 526, 'lowering body part': 559, 'action with ball': 564, 'stand up': 566, 'foot movements': 609, 'jog': 636, 'gesture': 648, 'sideways movement': 665, 'bend': 683, 'move up/down incline': 702, 'place something': 754, 'kick': 756, 'take/pick something up': 768, 'throw': 822, 'touching body part': 845, 'leg movements': 876, 'sit': 886, 'forward movement': 915, 'touch object': 947, 'stretch': 1009, 'circular movement': 1033, 'run': 1094, 'look': 1122, 'jump': 1124, 'raising body part': 1533, 'backwards movement': 1685, 'step': 1802, 't pose': 2299, 'interact with/use object': 2618, 'arm movements': 2676, 'turn': 2992, 'hand movements': 3648, 'stand': 5936, 'walk': 8487, 'transition': 14628}

We also tried the same without extra_train and extra_val json files (i.e we used only train, val, test json files of BABEL), but again the distribution doesn't match to the plot provided on the website
The distribution we got with this setup is as follows,
Total action segments : 243
Count of action segments : {'endure': 1, 'lead': 1, 'curtsy': 1, 'bartender behavior series': 1, 'reveal': 1, 'admire': 1, 'slash gesture series': 1, 'plant feet': 1, 'plead': 1, 'excite': 1, 'try': 1, 'conduct': 1, 'taunt': 1, 'vomit': 1, 'dive': 1, 'cower': 1, 'read': 1, 'leave': 1, 'weave': 1, 'shout': 2, 'charge': 2, 'disagree': 2, 'navigate': 2, 'glide': 2, 'laugh': 2, 'smell': 2, 'stick': 2, 'backwards': 2, 'moonwalk': 2, 'fidget': 2, 'noisy labels': 2, 'zip/unzip': 2, 'list body parts': 2, 'count': 2, 'rolls on ground': 2, 'feet movements': 2, 'fly': 2, 'pat': 3, 'tentative movements': 3, 'uncross': 3, 'lick': 3, 'hiccup': 3, 'fire gun': 4, 'remove': 4, 'headstand': 4, 'celebrate': 4, 'skate': 4, 'cut': 4, 'sneeze': 4, 'worry': 4, 'chop': 4, 'hang': 5, 'gain': 5, 'shave': 5, 'despair': 5, 'steady': 5, 'ride': 5, 'write': 6, 'cough': 6, 'sign': 6, 'juggle': 6, 'unknown': 6, 'fish': 6, 'think': 7, 'fight': 7, 'operate interface': 7, 'drive': 7, 'tiptoe': 7, 'prepare': 7, 'cry': 8, 'aim': 8, 'play': 8, 'chicken dance': 8, 'flail arms': 8, 'close something': 8, 'handstand': 8, 'yawn': 9, 'strafe': 9, 'listen': 9, 'drunken behavior': 9, 'pose': 9, 'dip': 9, 'rocking movement': 10, 'wobble': 10, 'release': 10, 'wash': 10, 'hurry': 10, 'waddle': 10, 'inward motion': 11, 'clasp hands': 11, 'shivering': 12, 'bump': 12, 'search': 12, 'hug': 13, 'fall': 13, 'give something': 13, 'zombie': 13, 'stroke': 13, 'wiggle': 14, 'stomp': 14, 'check': 14, 'mime': 15, 'eat': 15, 'pray': 15, 'draw': 16, 'interact with rope': 16, 'swipe': 17, 'tie': 17, 'style hair': 18, 'relax': 19, 'flip': 20, 'get injured': 20, 'stagger': 20, 'march': 21, 'yoga': 23, 'move misc. body part': 24, 'leap': 24, 'shrug': 25, 'open something': 26, 'sudden movement': 26, 'duck': 26, 'golf': 26, 'misc. action': 26, 'trip': 27, 'salute': 28, 'misc. abstract action': 29, 'slide': 29, 'to lower a body part': 31, 'limp': 31, 'flap': 32, 'communicate (vocalise)': 33, 'shuffle': 33, 'misc. activities': 34, 'dribble': 34, 'wait': 34, 'lunge': 35, 'mix': 35, 'cartwheel': 36, 'rub': 37, 'protect': 38, 'sneak': 38, 'sway': 40, 'swim': 41, 'jumping jacks': 43, 'side to side movement': 49, 'jump rope': 49, 'stances': 49, 'drink': 50, 'point': 50, 'skip': 50, 'support': 50, 'wrist movements': 51, 'press something': 52, 'play catch': 54, 'lie': 59, 'spread': 63, 'stop': 63, 'evade': 64, 'telephone call': 69, 'tap': 69, 'play instrument': 72, 'grab person': 73, 'rolling movement': 79, 'twist': 79, 'shoulder movements': 80, 'touch ground': 85, 'bow': 94, 'adjust': 95, 'crawl': 96, 'animal behavior': 99, 'move back to original position': 103, 'knock': 110, 'hit': 114, 'upper body movements': 118, 'crouch': 121, 'grab body part': 125, 'clap': 127, 'kneel': 127, 'martial art': 135, 'spin': 136, 'balance': 142, 'perform': 144, 'crossing limbs': 149, 'hop': 156, 'face direction': 162, 'play sport': 166, 'stumble': 167, 'shake': 167, 'squat': 186, 'scratch': 194, 'punch': 197, 'clean something': 209, 'sports move': 224, 'exercise/training': 230, 'poses': 241, 'greet': 249, 'catch': 252, 'touching face': 253, 'swing body part': 261, 'lean': 266, 'dance': 278, 'lift something': 280, 'knee movement': 290, 'move something': 294, 'waist movements': 296, 'wave': 310, 'grasp object': 352, 'jog': 356, 'action with ball': 448, 'head movements': 458, 'gesture': 475, 'kick': 491, 'move up/down incline': 516, 'a pose': 519, 'lowering body part': 528, 'stand up': 528, 'sideways movement': 547, 'throw': 588, 'foot movements': 588, 'bend': 629, 'run': 655, 'place something': 671, 'take/pick something up': 673, 'sit': 693, 'touching body part': 727, 'jump': 734, 'forward movement': 801, 'stretch': 815, 'leg movements': 835, 'circular movement': 860, 'touch object': 875, 'look': 983, 'backwards movement': 1434, 'raising body part': 1445, 'step': 1555, 't pose': 2156, 'interact with/use object': 2363, 'arm movements': 2444, 'turn': 2745, 'hand movements': 3456, 'stand': 5808, 'walk': 6262, 'transition': 14446}

**Comment by carjun** [comment]
Hi @chinnusai25 , thanks for your interest, and apologies for the delayed response. 

The plots and table on the website are only indicative of the data distribution, and unfortunately do not exactly correspond to the latest version of the dataset. The plots and tables were created based on a slightly earlier version of the dataset.
