### ISSUE TITLE
Action Recognition - PreProcess

### ISSUE THREAD

**Issue by BrianG13** [abhinanda-punnakkal/BABEL#6]
Hi,

Can you explain a little bit more about the pre-process step?
Did you use the 3D SMPL joints (24 joints?) for the pre-process?

None of the proposed joints indexes in the 2S-ACGN paper doesn't match to SMPL joint indexes.
Attached photo from paper:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/51123168/179426163-e3a434d4-34ba-496c-9d29-0cca613199ca.png">
https://arxiv.org/pdf/1805.07694.pdf

SMPL joints indexes:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/51123168/179426189-3d458526-0cd5-4a35-9071-063a61be99b4.png">

Could you give more details??
Thanks!

**Comment by abhinanda-punnakkal** [comment]
Hi, the details regarding the pre-processing is provided in section 6 of the supplementary material of the paper.
