### ISSUE TITLE
60 and 120 action categories

### ISSUE THREAD

**Issue by Jaceyxy** [abhinanda-punnakkal/BABEL#8]
Hi, Can I know what the 60 and 120 action categories refer to?

**Comment by carjun** [comment]
Hi @Jaceyxy , thanks for your interest. 

For BABEL-60, we use classes with indices [0, 59] (both inclusive), and for BABEL-120, we use classes with indices [0, 119] (both inclusive) [here](https://github.com/abhinanda-punnakkal/BABEL/blob/main/action_recognition/data/action_label_2_idx.json). 

We also considered a setting for 150-way classification. This is the reason why the  action_label_2_idx.json contains 150 classes.
